### ISSUE TITLE
Fix header scaling

### ISSUE THREAD

**Issue by peterjmartinson** [peterjmartinson/huygens-site#9]
The header doesn't scale for mobile.  This will _probably_ get fixed as we work on templates and styling, but let this issue be a reminder.
![image](https://github.com/peterjmartinson/huygens-site/assets/13594414/230b0ff3-ba4a-4abb-84cb-07704464a057)

**Comment by belcurv** [comment]
We'll fix this with CSS. There's already a media query to convert the nav items to the hamburger. We'll use something similar to scale the font size appropriately.

Take a stab at this is your want.
